import type { Metadata } from "next";

import "./globals.css";
import NavBar from "./components/navigation/navbar/NavBar";

export const metadata: Metadata = {
  title: "Michael Hayes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="jjk">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
